name: Claude Code PR review

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  review:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v0
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          custom_instructions: |
            Focus on:
            - Security vulnerabilities
            - Performance issues
            - Code quality and best practices
            - Test coverage
            - Documentation completeness
