name: Claude Code PR review

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v0
        with:
          anthropic_api_key: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # 下面这些参数以官方 README 为准，可设置模型、触发短语、模式等
          # model: claude-3-7-sonnet
          # trigger_phrase: "/claude review"
